### ISSUE TITLE
ng2-, and other standardizations 

### ISSUE THREAD

**Issue by NathanWalker** [jkuri/ng2-slimscroll#1]
This looks great, nice work! :)

It may be nice to name 'ng2-slimscroll' as that appears to be where the community is headed for third party libs.

I'll submit a PR next week to help with a few standardization things that may help this be more consumable and easier to integrate for others in future via angular cli, see this:
https://github.com/angular/angular-cli/issues/96

**Comment by valorkin** [comment]
:+1:

**Comment by jkuri** [comment]
Hi,

Thanks. I updated name to ng2-slimscroll as you suggested.

**Comment by NathanWalker** [comment]
Excellent thanks Jan!

**Comment by NathanWalker** [comment]
PR here:
https://github.com/jkuri/ng2-slimscroll/pull/2
