### ISSUE TITLE
Mobile support or fallback

### ISSUE THREAD

**Issue by doorman02** [jkuri/ng2-slimscroll#14]
Hi @jkuri thanks for making the slimscroll. I was wondering if you are planning to support mobile touch devices? E.g. if the slimscroll is being used on a mobile device to fallback to native scrollbar with overflow:scroll ?

**Comment by doorman02** [comment]
Hi @jkuri here is a suggestion to fallback to mobile scrollbar...
In the constructor prevent initalization...

 //  Check if mobile
    let testExp = new RegExp('Android|webOS|iPhone|iPad|' +
      'BlackBerry|Windows Phone|' +
      'Opera Mini|IEMobile|Mobile',
      'i');

    if (!testExp.test(navigator.userAgent)) {
      this.init();
    }

Cheers,

**Comment by jkuri** [comment]
@doorman02 thanks for this suggestion but I think it should be slimscrolls task to handle the mobile also. otherwise again all scrollbars will look different on mobile specific vendors and that's what I am trying to avoid.

**Comment by doorman02** [comment]
yes, I totally agree. I will use this fallback in the mean time.
Thanks for your help.

**Comment by rluckez** [comment]
any plans to mobile support?

**Comment by jkuri** [comment]
this should now be working with https://github.com/jkuri/ng2-slimscroll/pull/33

**Comment by doorman02** [comment]
@jkuri great thanks 👍

**Comment by sijithc40** [comment]
@jkuri Can I disable Slimscroll in Mobile and tablet ?

**Comment by jkuri** [comment]
currently not i believe. pr is welcome
