### ISSUE TITLE
Demo of Ng2-slimscroll is not good

### ISSUE THREAD

**Issue by khoanguyenlio** [jkuri/ng2-slimscroll#3]
When i click on scrollbar, it's not work fluency...

**Comment by jkuri** [comment]
Hi,
what do you mean with fluency? I tried again and it works okay for me. Which browser are you using?

**Comment by khoanguyenlio** [comment]
When you click on tre scrollbar then scroll or move mouse then click again. It's not work anymore

**Comment by jkuri** [comment]
Ok, I see, thanks for noticing. I will fix this and let you know.

**Comment by khoanguyenlio** [comment]
yeah! I am very interested in your ng2-slimscroll, I'm waiting for next commit :)) :+1:

**Comment by khoanguyenlio** [comment]
and I think we can modify like move mouse on the content-scrollbar is appear and when move out, it's gone. It could be better :dancers:

**Comment by khoanguyenlio** [comment]
I think these lines of code in slimscroll.directive.js:(35-49)
`bar = dom.getElementsByClassName(el, 'slimscroll-bar')[0];`
          `  bar.addEventListener('mousedown', function (e) {`
                `var top = parseFloat(dom.getStyle(bar, 'top'));`
              `  var pageY = e.pageY;`
             `   bar.addEventListener('mousemove', function () { _this.barDraggableListener(event, top, pageY); }, false);`
       `     }, false);`
          `  bar.addEventListener('mouseup', function () {`
              `  var newBar = bar.cloneNode(true);`
          `      bar.parentNode.replaceChild(newBar, bar);`
          `      _this.makeBarDraggable();`
        `    }, false);`
            `bar.addEventListener('selectstart', function (e) {`
        `        e.preventDefault();`
              `  e.stopPropagation();`
      `      }, false);`

**Comment by jkuri** [comment]
I think this is now resolved.
